# This is a basic workflow to help you get started with Actions

name: txnews

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  schedule:
     - cron: '*/7 0-23 * * *'
  watch:
     types: started

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v1

      # Runs a single command using the runners shell
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install

      # Runs a set of commands using the runners shell
      - name: '运行 【腾讯新闻】'
        run: |
          node Task/txnews.js
        env:
          TXNEWS_SIGN: ${{ secrets.TXNEWS_SIGN }}
          TXNEWS_COOKIE: ${{ secrets.TXNEWS_COOKIE }}
          TXNEWS_VIDEO: ${{ secrets.TXNEWS_VIDEO }}
