name: 中青看点

on:
  workflow_dispatch:
  schedule:
     - cron: '25 23 * * * *'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          cd ~/Scripts
          npm install
      - name: '运行 【中青看点】'
        run: |
          cd ~/Scripts
          node Task/youth.js
